### ISSUE TITLE
Non-Fungible Token Standard V2

### ISSUE THREAD

**Issue by KshitijChaudhary666** [onflow/flips#164]
https://github.com/onflow/flips/blob/1ae5b962f72b1e80999c48a91e8964456b83929a/application/20221219-nft-v2.md

https://github.com/onflow/flips/pull/56

**Comment by KshitijChaudhary666** [comment]
Hi @joshuahannan - do you know who's managing this FLIP? And what's the latest status?

**Comment by joshuahannan** [comment]
The FLIP is merged and implemented, so we can close this
