### ISSUE TITLE
Fungible Token Standard V2

### ISSUE THREAD

**Issue by KshitijChaudhary666** [onflow/flips#165]
https://github.com/onflow/flips/blob/06069e65e04f17fe173f9e81741ae6f6201fa4a1/application/20221219-ft-v2.md

https://github.com/onflow/flips/pull/55

**Comment by KshitijChaudhary666** [comment]
Hi @joshuahannan - also this one. Åre you the DRI? And what's the status?

**Comment by joshuahannan** [comment]
The FLIP is merged and implemented, so we can close this
