### ISSUE TITLE
FLIP 73: Event Streaming API (alpha version)

### ISSUE THREAD

**Issue by vishalchangrani** [onflow/flips#175]
https://github.com/onflow/flips/blob/main/protocol/20230309-accessnode-event-streaming-api.md

**Comment by KshitijChaudhary666** [comment]
@vishalchangrani @peterargue - has this FLIP been implemented?

**Comment by peterargue** [comment]
> @vishalchangrani @peterargue - has this FLIP been implemented?

yes
