### ISSUE TITLE
CADENCE: Attachments

### ISSUE THREAD

**Issue by pgebheim** [onflow/flips#19]
https://github.com/onflow/flips/blob/main/cadence/2022-09-21-attachments.md

**Comment by sisyphusSmiling** [comment]
I've gotten a chance to play around with Attachments as implemented and have found two primary features that would be very helpful and I can see others wanting in their contracts.

One is issue is that I'd like to define attachments for composite restricted types. So something like the following won't work, which I can see being very useful and even expected given how we define and use composite types in resources.
```
pub attachment Hat for INFT, MetadataViews.Resolver
```

I could design an attachment for use on any resource that implements a set of interfaces. Any one interface might not be sufficient for the functionality I'm after in my attachment, and defining a single implementation might be more limiting than I wish. My thought is this could greatly improve composability of attachments as it allows them to define more generalized base resources.

It would also be very helpful for a base resource to be able to access its attachments. So I could do something like 
```
pub resource NFT {
    ...
    pub fun resolveAttachmentView(attachmentType: Type, view: Type): &AnyStruct? {
        pre {
            attachmentType.isSubtype(of: &{MetadataViews.Resolver}): "Attachment is not a Resolver!"
        }
        // Get a reference to the attachment from the resource its attached to
        if let attachmentRef = self[attachmentType] {
            let attachmentView: &AnyStruct? = attachmentRef.invokeFunction<((Type): AnyStruct?)>("resolveView", args: view)
            return attachmentViews
        }
        return nil
    }
    ...
}
```

I didn't see anything in the Flip that explicitly eliminates the possibility of these two feature. I think devs would find them helpful, myself included!

**Comment by jasamba** [comment]
01/19 still in discussion

**Comment by j1010001** [comment]
- [ ] Release preview to get more feedback @turbolent

**Comment by j1010001** [comment]
Flip is accepted and closed
