### ISSUE TITLE
APPLICATION: Fungible Tokens Metadata

### ISSUE THREAD

**Issue by pgebheim** [onflow/flips#23]
https://github.com/onflow/flips/blob/main/flips/20220811-fungible-tokens-metadata.md

**Comment by franklywatson** [comment]
@franklywatson to follow up with @alilloig to confirm if this has been deployed

**Comment by alilloig** [comment]
confirmed https://flowscan.org/contract/A.f233dcee88fe0abe.FungibleTokenMetadataViews

**Comment by KshitijChaudhary666** [comment]
@alilloig @franklywatson - seems like this was "released"? Can we change the status of this pls to "Released"

**Comment by alilloig** [comment]
@KshitijChaudhary666 I don’t work here anymore mate
