### ISSUE TITLE
CADENCE: Capability Controllers

### ISSUE THREAD

**Issue by pgebheim** [onflow/flips#24]
PR: https://github.com/onflow/flow/pull/798

## Tasks
- [ ] Merge PR

**Comment by jasamba** [comment]
@janezpodhostnik any update on this FLIP?

**Comment by franklywatson** [comment]
@franklywatson to follow up with Janez and either break into two flips (AuthAccount capabilities) and leave this for the rest of the work

**Comment by j1010001** [comment]
Flip is accepted and PR closed
