### ISSUE TITLE
PROTOCOL: Automated Slot Assignment

### ISSUE THREAD

**Issue by pgebheim** [onflow/flips#29]
https://github.com/onflow/flips/blob/main/protocol/20220719-automated-slot-assignment.md

## Tasks
- [ ] Update this flip with the current spec and move to proposed

**Comment by jasamba** [comment]
01/19 is still in progress and should be done by end of the first week of Feb

**Comment by franklywatson** [comment]
Wrapping up PR and developing migration plan. Expect that testing will start week of 23rd Jan. Will be released around Feb 1

**Comment by jasamba** [comment]
@franklywatson, any update on this one?
