### ISSUE TITLE
CADENCE: Optional References to Indexed Accesses

### ISSUE THREAD

**Issue by pgebheim** [onflow/flips#33]
https://github.com/onflow/flips/blob/main/flips/20211208-cadence-remove-optional-reference.md

## Tasks
- [x] Check with @dsainati1 to see if we can [change status to Finalized](https://github.com/onflow/flips/pull/32) @jasamba

**Comment by jasamba** [comment]
Looks like it was finalized already

**Comment by dsainati1** [comment]
Yes, this has been finalized for a while.
