### ISSUE TITLE
CADENCE: Numeric Supertypes

### ISSUE THREAD

**Issue by pgebheim** [onflow/flips#34]
https://github.com/onflow/flips/blob/main/flips/20211210-cadence-numeric-supertypes.md

## Tasks
- [x] Check to see if this should be marked as Finalized

**Comment by pgebheim** [comment]
@SupunS -- Was this implemented and should this be marked as Finalized.

**Comment by SupunS** [comment]
Yes, this was implemented (https://github.com/onflow/cadence/pull/1360)

**Comment by pgebheim** [comment]
Applied change to FLIP markdown as well.
