### ISSUE TITLE
[BUG] Identify and document process for assigning FLIP numbers  

### ISSUE THREAD

**Issue by justinbarry** [onflow/flips#76]
### Current Behavior

I need help finding the process for assigning FLIP numbers to FLIPs. This [flip](https://github.com/onflow/flips/blob/main/flips/20220811-fungible-tokens-metadata.md) is "1087" while this [flip](https://github.com/onflow/flips/blob/main/protocol/20230110-accessnode-stake.md) is "FLIP-57". [This](https://github.com/onflow/flips/blob/main/flips/20201310-storage-fees.md) seems to be missing a flip number altogether.

### Expected Behavior

Update the readme and other process docs to reflect our decision.

**Comment by justinbarry** [comment]
All NEW FLIPs are numbered by the PR number submitted.

**Comment by KshitijChaudhary666** [comment]
Closing this issue as the readme was updated
